apiVersion: v1
kind: Service
metadata:
  name: task-manager
  namespace: algorithm-floyd
spec:
  type: NodePort
  ports:
    - name: https
      port: 30500
      targetPort: 30500
      nodePort: 30500
    - name: backend
      port: 30501
      targetPort: 30501
      nodePort: 30501
  selector:
    app: webapp-algorithm-floyd